### ISSUE TITLE
Update Alignment to produce CRAM files.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/cancer-genomics-workflow#118]

**Comment by tmooney** [comment]
This is done, except we should probably index the final CRAM file!

**Comment by malachig** [comment]
`samtools index sample.cram` appears to create:

sample.cram.crai

Maybe for convenience also create the following symlink that might be needed by some downstream steps?:

sample.crai -> sample.cram.crai

**Comment by jasonwalker80** [comment]
See #165 for adding the CRAM index.
