### ISSUE TITLE
Example data YAML for RNAseq

### ISSUE THREAD

**Issue by jasonwalker80** [genome/cancer-genomics-workflow#182]
In response to #178 make the corresponding example data YAML changes to illustrate usage and centralize the CWL inputs needed with example values for the RNAseq workflow.

**Comment by susannasiebert** [comment]
Yes! `/gscmnt/gc2764/cad/ssiebert/toil_test/arvados_trial/example_data/rnaseq/` has a `workflow.yaml` and a `stringtie.yml`
