### ISSUE TITLE
VEP annotated VCF: HGVS p. notation character encoding

### ISSUE THREAD

**Issue by jasonwalker80** [genome/cancer-genomics-workflow#195]

**Comment by jasonwalker80** [comment]
@dufeiyu can you provide an example please?

**Comment by jasonwalker80** [comment]
I found this relevant issue:
https://jira.gsc.wustl.edu/browse/CI-49

Specifically this comment: https://jira.gsc.wustl.edu/browse/CI-49?focusedCommentId=110605&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-110605

@dufeiyu is this the same issue?

**Comment by dufeiyu** [comment]
Yes, should be. Also Dr. Spencer provided the following case he found from toil cwl vep annotation output:
ENST00000331941.5:c.1260N>C|ENSP00000332180.5:p.Thr420%3D
That '%' character.

**Comment by jasonwalker80** [comment]
A text example is useful, but really we'd need an example VCF file to run through VEP and the subsequent python script.

**Comment by jasonwalker80** [comment]
It appears VEP is generating encoded characters since the '=' character would have special meaning in those fields of the VCF file. It seems the correct thing to do is translate the encoded character back to the user expected value when generating the TSV version of the variant list.

Title changed as appropriate.

**Comment by jasonwalker80** [comment]
@susannasiebert It seems that after #47 there are failures in executing the CWL workflow with the docker image mgibio/cle:v1.0.0. 

Example error:
```
Traceback (most recent call last):
  File "/usr/bin/add_annotations_to_table_helper.py", line 93, in <module>
    vep[chr][pos][ref][alt] = transcript_for_alt(transcripts, alleles_dict[alt])
KeyError: u'G'
```
For internal details, example data, discussion and more, see this JIRA issue:
https://jira.gsc.wustl.edu/browse/ITDEV-5037

**Comment by jasonwalker80** [comment]
This was reopened, but the cause was version skew between the Docker image that was used. Resolving.
