### ISSUE TITLE
Add tag to docker-cle and cancer-genomics-workflow for versioning

### ISSUE THREAD

**Issue by dufeiyu** [genome/cancer-genomics-workflow#196]
CLE need this for software version track.

**Comment by jasonwalker80** [comment]
https://github.com/genome/docker-cle/releases/tag/v1.0.0
https://github.com/genome/cancer-genomics-workflow/releases/tag/v1.0.0

I enabled the mgibio/cle DockerHub automated builds to trigger builds for each tag. The Docker Tag Name will be the same as the GitHub tag. I did this after making the first release. Any suggestion for building a new tagged version?

**Comment by jasonwalker80** [comment]
I tried the "Trigger" option next to the new setting. I'll see if that works....

**Comment by jasonwalker80** [comment]
Well, that didn't work:
https://hub.docker.com/r/mgibio/cle/builds/bucnnyjdinerunylncpnjzk/

**Comment by jasonwalker80** [comment]
I called out 'v1.0.0' explicitly and it's working. I must have had the regex wrong to build on any tag:
https://hub.docker.com/r/mgibio/cle/builds/bbrbgnvc9ftysudqbnuqli9/

**Comment by jasonwalker80** [comment]
The new build succeeded. I'm going to resolve this specific issue. We will continue to version other docker repos that are used in conjunction with the CWL.
