### ISSUE TITLE
Question: Should AF be represented as a ratio or percentage?

### ISSUE THREAD

**Issue by jasonwalker80** [genome/cancer-genomics-workflow#231]
Currently, the VAF in VCF tool uses a percentage. Common SNPs have allele frequencies represented as a ratio. Is there a standard or commonly preferred value?

**Comment by chrisamiller** [comment]
It used to be pretty evenly split between ratio and percentage, but I think ratio is winning out. It's worth polling the room, but I'd be okay with switching.

**Comment by jasonwalker80** [comment]
https://github.com/genome/docker-cle/pull/61
