### ISSUE TITLE
Variant Detection workflows should handle non-variant cases.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/cancer-genomics-workflow#237]
For MGI internal details, see:
https://jira.gsc.wustl.edu/browse/CIS-223

**Comment by tmooney** [comment]
Based on the details, it looks like the specific issue here is that [this header-processing block](https://github.com/Ensembl/ensembl-vep/blob/46e1afeccfb83e9b8948ddcdb2a0749792932bef/filter_vep#L192) is only triggered after reading the first non-header line.  Header processing should also happen if we reach EOF without having done it.

**Comment by tmooney** [comment]
One possible solution: https://github.com/tmooney/ensembl-vep/compare/release/91...tmooney:ensure_headers_are_output

**Comment by jasonwalker80** [comment]
Would we have to path our own version of Ensembl? I'd feel better if Ensembl accepted the pull request. Have we made a PR back to Ensembl?

**Comment by jasonwalker80** [comment]
A reminder this is due by the time we process the next MDS round.

**Comment by tmooney** [comment]
Another possible solution: genome/docker-cle#66 implements a wrapper script that only executes a command if the input VCF is non-empty.

**Comment by jasonwalker80** [comment]
Troubleshooting is ongoing, but for the most part this is resolved.
